// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksTracker.Migrations
{
    [DbContext(typeof(RazorPagesBookContext))]
    partial class RazorPagesBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("BooksTracker.Pages.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.HasIndex("CategoryTypeName");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.Category", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Type");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.CategoryType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryTypeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("CategoryType");

                    b.ToTable("CategoryType");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.Book", b =>
                {
                    b.HasOne("BooksTracker.Pages.Models.CategoryType", "CategoryType")
                        .WithMany("Books")
                        .HasForeignKey("CategoryTypeName");

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.CategoryType", b =>
                {
                    b.HasOne("BooksTracker.Pages.Models.Category", "Category")
                        .WithMany("CategoryTypes")
                        .HasForeignKey("CategoryType");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.Category", b =>
                {
                    b.Navigation("CategoryTypes");
                });

            modelBuilder.Entity("BooksTracker.Pages.Models.CategoryType", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
